import path from 'path';
import fs from 'fs';
import { execSync } from 'child_process';
import { Issue, FileChange, PRResult, ProcessingResult, IssueStatus } from '../github';
import { GitHubClient } from '../github/client';
import { TaskExecutor } from './executor';
import { config } from '../config';
import { getLogEmitter } from '../opencode/client';

const logEmitter = getLogEmitter();

function emitLog(line: string): void {
  logEmitter.emit('log', line);
}

export class IssueOrchestrator {
  private client: GitHubClient;
  private executor: TaskExecutor;
  private dryRun: boolean;
  private stats = { processed: 0, successful: 0, failed: 0 };

  constructor(client: GitHubClient, dryRun: boolean = false) {
    this.client = client;
    this.dryRun = dryRun;
    this.executor = new TaskExecutor(client);
  }

  async processIssue(issue: Issue): Promise<ProcessingResult> {
    const startTime = Date.now();
    emitLog(`\n🎯 Processing issue #${issue.number}: ${issue.title}`);

    const mainBranch = 'main';

    try {
      // Step 1: Mark as in progress
      await this.markInProgress(issue.number);

      // Ensure we're on main before starting
      if (!this.dryRun) {
        await this.client.gitCheckout(mainBranch);
      }

      // Step 3: Execute the task with OpenCode (which creates branch, implements, commits)
      emitLog('🤖 Executing task with OpenCode...');
      const execResult = await this.executor.execute(issue, this.dryRun);
      const { changes, branchName, error } = execResult;

      if (error) {
        emitLog(`❌ Error from executor: ${error}`);
        throw new Error(error);
      }

      if (changes.length === 0) {
        console.log('⚠️ No changes made');
        
        if (!this.dryRun) {
          await this.client.gitCheckout(mainBranch);
        }
        
        return {
          issueNumber: issue.number,
          success: false,
          message: 'No changes were made',
          changes: [],
          durationMs: Date.now() - startTime,
        };
      }

      // Step 4: Push the branch (created by OpenCode)
      if (!this.dryRun && branchName) {
        console.log(`📤 Pushing branch: ${branchName}`);
        
        // Push branch to remote
        if (!(await this.client.gitPush(branchName))) {
          throw new Error(`Failed to push branch: ${branchName}`);
        }
        
        // Create remote branch if needed
        await this.client.createBranch(branchName);
      }

      // Step 5: Create PR
      const prResult = await this.createPR(issue, branchName || 'unknown', changes);

      // Step 6: Mark as completed
      await this.markCompleted(issue.number, prResult);

      // Update stats
      this.stats.processed++;
      if (prResult.success) {
        this.stats.successful++;
      } else {
        this.stats.failed++;
      }

      const duration = Date.now() - startTime;
      console.log(`✅ Completed in ${duration}ms`);

      if (!this.dryRun) {
        await this.client.gitCheckout(mainBranch);
      }

      return {
        issueNumber: issue.number,
        success: prResult.success,
        message: `Completed: ${prResult.message}`,
        changes,
        prResult,
        durationMs: duration,
      };
    } catch (error: any) {
      console.error(`❌ Failed to process issue #${issue.number}:`, error);

      await this.markFailed(issue.number, error.message);
      this.stats.processed++;
      this.stats.failed++;

      if (!this.dryRun) {
        await this.client.gitCheckout(mainBranch);
      }

      return {
        issueNumber: issue.number,
        success: false,
        message: error.message,
        changes: [],
        error: error.message,
        durationMs: Date.now() - startTime,
      };
    }
  }

  private async markInProgress(issueNumber: number): Promise<void> {
    console.log(`📌 Marking issue #${issueNumber} as in-progress`);

    if (this.dryRun) return;

    await this.client.removeLabel(issueNumber, config.labels.ready);
    await this.client.addLabels(issueNumber, [config.labels.implementing]);
    await this.client.addComment(
      issueNumber,
      `🤖 Agent started working on this issue at ${new Date().toUTCString()}`
    );
  }

  private async createPR(
    issue: Issue,
    branchName: string,
    changes: FileChange[]
  ): Promise<PRResult> {
    const changedFiles = changes.map((c) => `- \`${c.path}\` (${c.operation})`).join('\n');

    const prBody = `## Summary
${issue.body}

## Changes Made
${changedFiles || '- See implementation details'}

## Checklist
- [ ] Tests added/updated
- [ ] Code follows project style
- [ ] Documentation updated

---
*This PR was automatically generated by GitHub Agent Orchestrator*
*Issue: #${issue.number} | @${issue.author}*
`;

    const prTitle = `Fix #${issue.number}: ${issue.title}`;
    console.log(`📝 Creating PR: ${prTitle}`);

    if (this.dryRun) {
      console.log(`[DRY RUN] Would create PR: ${prTitle}`);
      return { success: true, branchName, message: '[DRY RUN] PR would be created' };
    }

    return this.client.createPullRequest(prTitle, prBody, branchName);
  }

  private async markCompleted(issueNumber: number, prResult: PRResult): Promise<void> {
    console.log(`✅ Marking issue #${issueNumber} as completed`);

    if (this.dryRun) return;

    await this.client.removeLabel(issueNumber, config.labels.implementing);
    await this.client.addLabels(issueNumber, [config.labels.done]);

    if (prResult.success) {
      await this.client.addComment(
        issueNumber,
        `🎉 **Issue resolved!**

PR created: #{prResult.prNumber}

Please review and merge when ready!`
      );
    }
  }

  private async markFailed(issueNumber: number, error: string): Promise<void> {
    console.error(`❌ Marking issue #${issueNumber} as failed: ${error}`);

    if (this.dryRun) return;

    await this.client.removeLabel(issueNumber, config.labels.implementing);
    await this.client.addLabels(issueNumber, [config.labels.failed]);

    const errorHint = this.getErrorHint(error);

    await this.client.addComment(
      issueNumber,
      `⚠️ **Processing failed**

**Error:** ${error}

${errorHint}

Please review and re-open if needed.`
    );
  }

  private getErrorHint(error: string): string {
    const lowerError = error.toLowerCase();
    
    if (lowerError.includes('model') || lowerError.includes('api key') || lowerError.includes('auth')) {
      return '**Hint:** This appears to be a configuration issue. Please check that the AI model is properly configured and the API key is valid.';
    }
    if (lowerError.includes('timeout')) {
      return '**Hint:** The operation timed out. The task may be too complex or the AI service may be slow. Try breaking the issue into smaller parts.';
    }
    if (lowerError.includes('network') || lowerError.includes('connection')) {
      return '**Hint:** There was a network issue. Please check your internet connection and try again.';
    }
    if (lowerError.includes('no changes') || lowerError.includes('could not implement')) {
      return '**Hint:** The AI could not determine what changes to make. Please provide more specific information about what files need to be changed and what the expected behavior should be.';
    }
    return '**Hint:** Check the agent logs for more details about what went wrong.';
  }

  getStats() {
    return {
      ...this.stats,
      successRate:
        this.stats.processed > 0
          ? `${((this.stats.successful / this.stats.processed) * 100).toFixed(1)}%`
          : 'N/A',
    };
  }
}
