import path from 'path';
import fs from 'fs';
import { Issue, FileChange, PRResult, ProcessingResult, IssueStatus } from '../github';
import { GitHubClient } from '../github/client';
import { TaskExecutor } from './executor';
import { config } from '../config';

export class IssueOrchestrator {
  private client: GitHubClient;
  private executor: TaskExecutor;
  private dryRun: boolean;
  private stats = { processed: 0, successful: 0, failed: 0 };

  constructor(client: GitHubClient, dryRun: boolean = false) {
    this.client = client;
    this.dryRun = dryRun;
    this.executor = new TaskExecutor(client);
  }

  async processIssue(issue: Issue): Promise<ProcessingResult> {
    const startTime = Date.now();
    console.log(`\n🎯 Processing issue #${issue.number}: ${issue.title}`);

    try {
      // Step 1: Mark as in progress
      await this.markInProgress(issue.number);

      // Step 2: Create branch from main
      const branchName = this.generateBranchName(issue);
      console.log(`🌿 Creating branch: ${branchName}`);

      if (!this.dryRun) {
        // Always start from latest main
        if (!(await this.client.switchToMainAndCreateBranch(branchName))) {
          throw new Error(`Failed to create branch: ${branchName}`);
        }
      }

      // Step 3: Execute the task
      console.log('⚙️ Executing task...');
      const changes = await this.executor.execute(issue, this.dryRun);

      // If no changes, agent asked for clarification
      if (changes.length === 0) {
        console.log('⚠️ No changes made - agent needs clarification');
        
        // Go back to main and cleanup
        if (!this.dryRun) {
          await this.client.gitCheckout('main');
        }
        
        return {
          issueNumber: issue.number,
          success: false,
          message: 'Agent needs clarification before proceeding',
          changes: [],
          durationMs: Date.now() - startTime,
        };
      }

      console.log(`📝 Made ${changes.length} change(s)`);

      // Step 4: Commit and push
      if (!this.dryRun) {
        console.log('📤 Committing...');
        if (!(await this.client.gitCommit(`Fix #${issue.number}: ${issue.title}`))) {
          throw new Error('Failed to commit changes');
        }

        if (!(await this.client.gitPush(branchName))) {
          throw new Error('Failed to push changes');
        }

        // Create remote branch
        await this.client.createBranch(branchName);
      }

      // Step 5: Create PR
      const prResult = await this.createPR(issue, branchName, changes);

      // Step 6: Mark as completed
      await this.markCompleted(issue.number, prResult);

      // Update stats
      this.stats.processed++;
      if (prResult.success) {
        this.stats.successful++;
      } else {
        this.stats.failed++;
      }

      const duration = Date.now() - startTime;
      console.log(`✅ Completed in ${duration}ms`);

      return {
        issueNumber: issue.number,
        success: prResult.success,
        message: `Completed: ${prResult.message}`,
        changes,
        prResult,
        durationMs: duration,
      };
    } catch (error: any) {
      console.error(`❌ Failed to process issue #${issue.number}:`, error);

      await this.markFailed(issue.number, error.message);
      this.stats.processed++;
      this.stats.failed++;

      return {
        issueNumber: issue.number,
        success: false,
        message: error.message,
        changes: [],
        error: error.message,
        durationMs: Date.now() - startTime,
      };
    }
  }

  private generateBranchName(issue: Issue): string {
    const cleanTitle = issue.title
      .toLowerCase()
      .replace(/[^\w\s-]/g, '')
      .replace(/\s+/g, '-')
      .substring(0, 50);
    return `agent/issue-${issue.number}/${cleanTitle}`;
  }

  private async markInProgress(issueNumber: number): Promise<void> {
    console.log(`📌 Marking issue #${issueNumber} as in-progress`);

    if (this.dryRun) return;

    await this.client.removeLabel(issueNumber, config.labels.ready);
    await this.client.addLabels(issueNumber, [config.labels.implementing]);
    await this.client.addComment(
      issueNumber,
      `🤖 Agent started working on this issue at ${new Date().toUTCString()}`
    );
  }

  private async createPR(
    issue: Issue,
    branchName: string,
    changes: FileChange[]
  ): Promise<PRResult> {
    const changedFiles = changes.map((c) => `- \`${c.path}\` (${c.operation})`).join('\n');

    const prBody = `## Summary
${issue.body}

## Changes Made
${changedFiles || '- See implementation details'}

## Testing
<!-- TODO: Add testing notes -->

## Checklist
- [ ] Tests added/updated
- [ ] Code follows project style
- [ ] Documentation updated

---
*This PR was automatically generated by GitHub Agent Orchestrator*
*Issue: #${issue.number} | @${issue.author}*
`;

    const prTitle = `Fix #${issue.number}: ${issue.title}`;
    console.log(`📝 Creating PR: ${prTitle}`);

    if (this.dryRun) {
      console.log(`[DRY RUN] Would create PR: ${prTitle}`);
      return { success: true, branchName, message: '[DRY RUN] PR would be created' };
    }

    return this.client.createPullRequest(prTitle, prBody, branchName);
  }

  private async markCompleted(issueNumber: number, prResult: PRResult): Promise<void> {
    console.log(`✅ Marking issue #${issueNumber} as completed`);

    if (this.dryRun) return;

    await this.client.removeLabel(issueNumber, config.labels.implementing);
    await this.client.addLabels(issueNumber, [config.labels.done]);

    if (prResult.success) {
      await this.client.addComment(
        issueNumber,
        `🎉 **Issue resolved!**

PR created: #${prResult.prNumber}

## Review Checklist
- [ ] Code changes are correct and complete
- [ ] Tests pass locally
- [ ] Documentation is updated
- [ ] No breaking changes

Please review and merge when ready!`
      );
    }
  }

  private async markFailed(issueNumber: number, error: string): Promise<void> {
    console.error(`❌ Marking issue #${issueNumber} as failed`);

    if (this.dryRun) return;

    await this.client.removeLabel(issueNumber, config.labels.implementing);
    await this.client.addLabels(issueNumber, [config.labels.failed]);

    await this.client.addComment(
      issueNumber,
      `⚠️ **Processing failed**

Error: ${error}

Please review and re-open if needed.`
    );
  }

  getStats() {
    return {
      ...this.stats,
      successRate:
        this.stats.processed > 0
          ? `${((this.stats.successful / this.stats.processed) * 100).toFixed(1)}%`
          : 'N/A',
    };
  }
}
